trigger:
  - master

pool:
  vmImage: "ubuntu-16.04"
  
variables:
  registryConnection: mymicroserviceconnection
  imageName: mydotnetmicroservice

steps:
  - task: Docker@2
    displayName: "Build image"
    inputs:
      repository: $(imageName)
      containerRegistry: $(registryConnection)
      command: buildAndPush
      Dockerfile: Dockerfile
      tags: $(Build.BuildNumber)

  - task: PublishBuildArtifacts@1
    displayName: "Publish artifacts"
    inputs:
      pathtoPublish: manifests
      artifactName: "manifests"
      publishLocation: "Container"