apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydotnetmicroservice 
  labels:
    app: mydotnetmicroservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydotnetmicroservice 
  template:
    metadata:
      labels:
        app: mydotnetmicroservice 
    spec:
      containers:
        - name: search
          image: mymicroserviceregistrybkr.azurecr.io/mydotnetmicroservice 
          ports:
            - containerPort: 80
              name: http
          imagePullPolicy: Always